### ISSUE TITLE
Use tools for basic music production

### ISSUE THREAD

**Issue by JoelNash-Xuuki** [JoelNash-Xuuki/DAW#1]
# Epic:
Basic tools to record musical ideas

### Tasks

- [ ] Create classes for recording
- [ ] Create classes for mix
- [ ] Create basic an intereface on command programme.

# Acceptance Criteria ( data invariants & operations )
